### PR TITLE
CPP-398  n-gage - Address regular expression DoS vulnerability

### PR DESCRIPTION
**Pull request by emortong**
[Ticket CPP-398](https://financialtimes.atlassian.net/browse/CPP-398)

This is a task to address a regular expression denial of service vulnerability reported via Snyk:

Screenshot 2020-12-01 at 14 28 01

### CODE REVIEW

**Comment by apaleslimghost** [comment]
i'm wary of updating major versions of things like stylelint, have you tested this on a repo that uses it? i've had a scan through the changelog, and there's one breaking change that could affect people:

> # 12.0.0
> - Removed: ignoring bower_components folder by default (stylelint/stylelint#4384).

this could break things if it starts linting Origami components with our rules, so we might need to update our config

**Comment by antonsamper** [comment]
As the stylelint config from `n-gage` is used in other packages, do you know if this update has an impact on the other repos? It might be worth checking

**Comment by emortong** [comment]
> i'm wary of updating major versions of things like stylelint, have you tested this on a repo that uses it? i've had a scan through the changelog, and there's at least one breaking change that could affect people:
> 
> > # 12.0.0
> > 
> > * Removed: ignoring bower_components folder by default ([stylelint/stylelint#4384](https://github.com/stylelint/stylelint/pull/4384)).
> 
> this could break things if it starts linting Origami components with our rules, so we might need to update our config

I tested using `n-conversion-forms` by adding my own `.stylelintrc` since I could not find repos using `n-gage` and having a `.stylelintrc` but yes, that change could break things, thanks for pointing it out @apaleslimghost. Do you know off the top of you head any project using `n-gage` and having a `.stylelintrc` ?

**Comment by apaleslimghost** [comment]
i don't know of any that have their own `.stylelintrc`, but loads of apps use the one distributed with `n-gage`, which is installed when apps add it to their `.gitignore`. `next-article` does this for one example

**Comment by emortong** [comment]
@apaleslimghost great! thank you, I'll take a look at it :)

**Comment by emortong** [comment]
tested using `next-article` and it only gave me two deprecation warnings, made the fix in `n-gage`'s `stylelintrc`

if there are any lint errors that come up, running `stylelint client/**.scss --fix `should fix them.

Screenshot 2020-12-17 at 21 04 05

**Review by apaleslimghost — APPROVED** [review]

**Pull request merged**
